export const drugCategories = [
  "Acid Reflux",
  "Alcohol Dependence",
  "Allergies",
  "ALS",
  "Angina",
  "Anti-bacterial",
  "Anti-fungal",
  "Anti-Inflammation",
  "Anti-Parasitic",
  "Anti-viral",
  "Antihyperlipidemic",
  "Arthritis",
  "Asthma/COPD",
  "Birth Control",
  "Blood Thinner",
  "Bone Health",
  "Breast Cancer",
  "Burns",
  "Cancer",
  "Chronic Dry Eye",
  "Colonoscopy Preparation",
  "Constipation",
  "Cough",
  "Crohn's Disease",
  "Dementia",
  "Dental Care",
  "Diabetes",
  "Diuretic",
  "Erectile Dysfunction",
  "Gallstone",
  "Gastrointestinal",
  "Glaucoma",
  "Gout",
  "Hair & Skin Health",
  "Heart Failure",
  "Heart Health",
  "Hemorrhoids",
  "High Blood Pressure",
  "High Cholesterol",
  "HIV",
  "Hormone Therapy",
  "Hyponatremia",
  "Incontinence",
  "Infection",
  "Iron Overload",
  "Kidney Disease",
  "Leukemia",
  "Low Blood Pressure",
  "Low Potassium",
  "Men's Health",
  "Mental Health",
  "Migraines",
  "Multiple sclerosis",
  "Muscle Relaxants",
  "Musculoskeletal",
  "Nausea",
  "Neurological",
  "Opioid Dependence",
  "Organ Transplant",
  "Pain & Inflammation",
  "Parkinson's Disease",
  "Prostate",
  "Restless Leg Syndrome",
  "Rheumatoid Arthritis",
  "Seizures",
  "Sleep Aid",
  "Smoking Cessation",
  "Steroid",
  "Stroke Prevention",
  "Thyroid",
  "Urinary Symptoms",
  "Vitamin",
  "Weight Loss",
];